language: node_js
node_js:
  - "0.10"
  - "0.8"

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - sudo apt-get update
 - sudo apt-get install gcc-4.7 g++-4.7 libprotobuf7 libprotobuf-dev protobuf-compiler

install:
 - npm install mocha

before_script:
 - CXX=g++-4.7 npm install
 - make test

script:
 - make clean
 - npm install --std=0 --lazy=0
 - make test