version: 2

step-library:
  - &install-apt-deps
      run:
          name: Install apt dependencies
          command: |
            set +e
            apt-get update -y
            apt-get install -y build-essential python git curl
            curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
            echo 'deb http://dl.yarnpkg.com/debian/ stable main' | tee /etc/apt/sources.list.d/yarn.list
            apt-get update -y
            apt-get -y install yarn

  - &install-node
      run:
          name: Install node
          command: |
            set +e
            echo 'export NVM_DIR=${HOME}/.nvm' >> $BASH_ENV
            source ${BASH_ENV}
            mkdir -p ${NVM_DIR}
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            echo "[ -s \"${NVM_DIR}/nvm.sh\" ] && . \"${NVM_DIR}/nvm.sh\"" >> $BASH_ENV
            source ${BASH_ENV}
            nvm install ${NODE_VERSION}
            nvm alias default ${NODE_VERSION}

  - &yarn-install
      run:
          name: "Yarn install"
          command: |
            set +e
            yarn install

  - &yarn-test
      run:
          name: "Yarn lint/coverage/bench"
          command: |
            set +e
            yarn run lint
            yarn run coverage
            yarn run bench
          no_output_timeout: 12000

jobs:
    node6:
        docker:
            - image: ubuntu:18.04
        environment:
            NODE_VERSION: 6
        steps:
            - *install-apt-deps
            - *install-node
            - checkout
            - *yarn-install
            - *yarn-test

workflows:
    version: 2
    build:
        jobs:
            - node6
